### ISSUE TITLE
Album art not always showing up depending on the song

### ISSUE THREAD

**Issue by Khosraw** [JakeStanger/mpd-discord-rpc#29] opened 2022-06-17 01:14 UTC
So first of all, I love the new update. I was planning on trying to learn Rust and add the feature myself, but looks like someone read my mind. It's great, but I've noticed that some songs won't have their album art displayed. 

Here are images showing just one example of it:
![Screenshot_2022-06-16-08-15-59_1920x1080](https://user-images.githubusercontent.com/53713571/174203083-1a7a9e24-f6a6-45eb-b73d-0c4b8f211e98.png)

You can see that the album art is not displayed next to the RPC itself.

![Screenshot_2022-06-16-20-06-20_1920x1080](https://user-images.githubusercontent.com/53713571/174202554-944ca474-4d5f-490c-8332-6f1c052af17f.png)
Yet `dunst` is able to pickup the album art just fine here.

This isn't the only song where this happens. This might be because of the method that's being used to get the album art. The album art that is being pickup is included in the song file itself, but if `mpd-discord-rpc` is using some third-party to fetch album art, then that might be why it's not picking up the album art. I'm not sure if it is possible, but the program could try fetching the album art from the file itself assuming it's not already trying to do that. I'm not educated on the matter, but I'm sure you will be able to enlighten the idea further.

Edit: It seems to be a 50:50 for me as far as which songs have their album art shown.

**Comment by Kranzes** [comment] 2022-06-17 01:20
I have to add that so far all of my music with proper tags like `Album Artist`, `Artist`, `Album`,`Track` etc, worked fine and it showed the correct album cover.
![image](https://user-images.githubusercontent.com/56614642/174203397-de3622d4-0870-44f0-b36d-73a38ef3c0d1.png)

**Comment by Khosraw** [comment] 2022-06-17 01:24
Looked through the code and it looks like it's using `MUSICBRAINZ` to fetch the album art. So, my suggestion might be worth noting?

**Comment by Kranzes** [comment] 2022-06-17 01:27
My library doesn't have the `MUSICBRAINZ` tag anyway. I believe it fall-backs to searching up the album art for the name of the `Album` tag.

**Comment by Khosraw** [comment] 2022-06-17 01:32
I believe less popular songs that are usually not listed on MusicBrainz don't have their album art on there, so they tend to not be displayed.

**Comment by Kranzes** [comment] 2022-06-17 01:34
Maybe it would be possible to get the album art if it's embedded into the music file as you said before, or even if there is a file like `{folder,cover}.{jpg,png}` in the directory of the album.

**Comment by JakeStanger** [comment] 2022-06-17 08:10
The crux of the issue is that (as far as I'm aware, I'm very happy to be proved wrong) discord only accepts images in two ways:

- assets pre-defined in the developer portal app registration
- a full HTTPS URL

This effectively rules out local images unfortunately, which is a darn shame because that'd even allow me to use MPD's built-in albumart commands. The one thing that would be possible is to have your local covers automatically uploaded to some central online location (eg AWS S3), but that would be out of scope for this program.

The reason I chose MusicBrainz is because they're the only major album art API that don't require authentication, and I'd like the feature to Just Werk™ without any setup.  This does come with the added advantage of MPD supporting their tags, and also their database is fully open so you can contribute your own changes if anything is wrong/missing.

The process to get the art is as described - first the MUSICBRAINZ_ALBUMID tag is read from the local track, and then it falls back to searching for the album/artist name on MusicBrainz (and takes the first result). This means so long as your tags are accurate, you should get good results.

A good way to set the MUSICBRAINZ_ALBUMID tag in bulk is using their [Picard](https://picard.musicbrainz.org/) software. Just make sure you configure it to not overwrite any tags you don't want changed!

**Comment by Kranzes** [comment] 2022-06-17 11:53
The current implementation works great for me so I can't complain.

**Comment by Khosraw** [comment] 2022-06-17 16:20
Alright, guess I'm uploading some album art today...

**Comment by JakeStanger** [comment] 2022-06-17 16:44
I'll close this issue for now since, as far as I'm aware, that's the only real solution. If anybody has any ideas, feel free to stick them below and I'll re-open.

**Closed by JakeStanger** 2022-06-17 16:44 UTC
